;; Copyright (C) 2020  David Arroyo Menéndez

;; Author: David Arroyo Menéndez <davidam@gnu.org>
;; Maintainer: David Arroyo Menéndez <davidam@gnu.org>

;; This file is software with freedom of class; you can
;; redistribute it and/or modify it  only for the working
;; class under the terms of the Working Class License
;; published by David Arroyo Menéndez.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; Working Class License for more details.
;; You should have received a copy of the Working Class License along
;; with examples about Emacs Lisp; see the file COPYING. If not, see

;; <https://github.com/davidam/workingclasslicense>.

(defun davidam-insert-org-beamer-header(title author language description keywords)
  (interactive "sTitle: \nsAuthor: \nsLanguage: \nsDescription: \nsKeywords: ")
  (insert (concat "#+TITLE: " title "\n"))
  (insert (concat "#+AUTHOR: " author "\n"))
  (insert (concat "#+EMAIL: " user-mail-address "\n"))
  (insert (concat "#+DATE: [" (format-time-string "%Y-%m-%d") "] \n"))
  (insert (concat "#+LANGUAGE: " language "\n"))
  (insert (concat "#+KEYWORDS: " keywords "\n"))
  (insert "#+LaTeX_CLASS: beamer \n")
  (insert "#+LaTeX_CLASS_OPTIONS: [presentation] \n")
  (insert "#+BEAMER_THEME: Madrid \n")
  (insert "#+COLUMNS: %45ITEM %10BEAMER_ENV(Env) %10BEAMER_ACT(Act) %4BEAMER_COL(Col) %8BEAMER_OPT(Opt) \n"))

(defun davidam-insert-org-header(title author language)
  (interactive "sTitle: \nsAuthor: \nsLanguage: \n")
  (insert (concat "#+TITLE: " title "\n"))
  (insert (concat "#+AUTHOR: " author "\n"))
  (insert (concat "#+EMAIL: " user-mail-address "\n"))
  (insert (concat "#+LANGUAGE: " language "\n"))
  (insert "#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='../css/org.css' />\n"))

(defun davidam-insert-bin(language)
  (interactive "sWrite a language (python2, python3, shell, bash, ruby): \n")
  (setq comment "#")
  (cond ((string-prefix-p "python" language)
	 (insert (concat comment "!/usr/bin/" language "\n"))
	 (insert (concat comment " -*- coding: utf-8 -*-\n")))
	((string= language "shell")
	 (insert (concat comment "!/bin/sh\n")))
	((string= language "bash")
	 (insert (concat comment "!/bin/bash\n")))
	((string= language "ruby")
	 (insert (concat comment "!/usr/bin/" language "\n"))
	 (insert "# coding: utf-8 \n"))))

(defun davidam-insert-damegender-test(test)
  (interactive "sWrite damegender test\n")
  (insert (concat
	   "if ! cmp files/tests/" test ".txt files/tests/" test "-$(date \"+%Y-%m-%d-%H\").txt >/dev/null 2>&1 \n"))
  (insert "then \n")
  (insert "    echo \"" test " test is failing\"\n")
  (insert "else\n")
  (insert "    echo \"" test " test is ok\"\n")
  (insert "fi\n"))

(defun davidam-insert-jest-test(test expectvar1 expectvar2)
  (interactive "sWrite jest title test \nsExpect variable 1: \nsExpect variable 2: \n")
  (insert "test('" test "', () => {\n")
  (insert "  expect(" expectvar1 ").toEqual('" expectvar2 "');\n")
  (insert "});"))  

(defun davidam-insert-copyright-note(language license name filename)
  (interactive "sLanguage (python, bash, lisp, sql, js): \nsLicense (gplv3, mit, fl, wcl): \nsSoftware Name: \nsFilename of license (COPYING, LICENSE, GPL.txt, ...): \n")
  (setq comment "")
  (cond ((or (string-prefix-p language "sh") (string= language "bash") (string-prefix-p language "python"))
	 (setq comment "# "))
	((string= language "lisp")
	 (setq comment ";;"))
	((string= language "sql")
	 (setq comment "-- "))
	((or (string= language "javascript") (string= language "js") (string= language "c"))
	 (setq comment "//")))
  (cond ((string= license "gplv3")
	 (insert (concat comment " Copyright (C) " (format-time-string "%Y") " " user-full-name "\n"))
	 (insert "\n")
	 (insert (concat comment " Author: " user-full-name " <" user-mail-address "> \n"))
	 (insert (concat comment " Maintainer: " user-full-name " <" user-mail-address "> \n"))
	 (insert (concat comment " This file is free software; you can redistribute it and/or modify\n"))
	 (insert (concat comment " it under the terms of the GNU General Public License as published by\n"))
	 (insert (concat comment " the Free Software Foundation; either version 3, or (at your option)\n"))
	 (insert (concat comment " any later version.\n"))
	 (insert (concat comment "\n"))
	 (insert (concat comment " This file is distributed in the hope that it will be useful,\n"))
	 (insert (concat comment " but WITHOUT ANY WARRANTY; without even the implied warranty of\n"))
	 (insert (concat comment " MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"))
	 (insert (concat comment " GNU General Public License for more details.\n"))
	 (insert (concat comment "\n"))
	 (insert (concat comment " You should have received a copy of the GNU General Public License\n"))
	 (insert (concat comment " along with " name "; see the file " filename ".  If not, write to\n"))
	 (insert (concat comment " the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, \n"))
	 (insert (concat comment " Boston, MA 02110-1301 USA,\n")))
	((string= license "fl")
	 (insert (concat comment " Copyright (C) " (format-time-string "%Y") " " user-full-name "\n"))
	 (insert "\n")
	 (insert (concat comment " Author: " user-full-name " <" user-mail-address "> \n"))
	 (insert (concat comment " Maintainer: " user-full-name " <" user-mail-address "> \n"))
	 (insert (concat comment " You can share, copy and modify this software if you are a woman or you\n"))
	 (insert (concat comment " are " user-full-name " and you include this note.\n")))
	((string= license "mit")
	 (insert (concat comment " Copyright (C) " (format-time-string "%Y") " " user-full-name "\n"))
	 (insert "\n")
	 (insert (concat comment " Author: " user-full-name " <" user-mail-address "> \n"))
	 (insert (concat comment " Maintainer: " user-full-name " <" user-mail-address "> \n"))
	 (insert (concat comment " Permission is hereby granted, free of charge, to any person obtaining\n"))
	 (insert (concat comment " a copy of this software and associated documentation files (the '" name "'\n"))
	 (insert (concat comment " to deal in the Software without restriction, including without limitation\n"))
	 (insert (concat comment " the rights to use, copy, modify, merge, publish, distribute, sublicense,\n"))
	 (insert (concat comment " and/or sell copies of the Software, and to permit persons to whom\n"))
	 (insert (concat comment " the Software is furnished to do so, subject to the following conditions:\n"))
	 (insert (concat comment " \n"))
	 (insert (concat comment " The above copyright notice and this permission notice shall be included\n"))
	 (insert (concat comment " in all copies or substantial portions of the Software.\n"))
	 (insert (concat comment " \n"))
	 (insert (concat comment " THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"))
	 (insert (concat comment " IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"))
	 (insert (concat comment " FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"))
	 (insert (concat comment " AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"))
	 (insert (concat comment " LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\n"))
	 (insert (concat comment " FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n"))
	 (insert (concat comment " DEALINGS IN THE SOFTWARE.\n")))
	((string= license "wcl")
	 (insert (concat comment " Copyright (C) " (format-time-string "%Y") " " user-full-name "\n"))
	 (insert "\n")
	 (insert (concat comment " Author: " user-full-name " <" user-mail-address "> \n"))
	 (insert (concat comment " Maintainer: " user-full-name " <" user-mail-address "> \n"))
	 (insert (concat comment " This file is software with freedom of class; you can \n"))
	 (insert (concat comment " redistribute it and/or modify it  only for the working \n"))
	 (insert (concat comment " class under the terms of the Working Class License \n"))
	 (insert (concat comment " published by David Arroyo Menéndez.\n"))
	 (insert (concat comment " This file is distributed in the hope that it will be useful,\n"))
	 (insert (concat comment " but WITHOUT ANY WARRANTY; without even the implied warranty of\n"))
	 (insert (concat comment " MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"))
	 (insert (concat comment " Working Class License for more details.\n"))
	 (insert (concat comment " You should have received a copy of the Working Class License along\n"))
	 (insert (concat comment " with examples about Bash; see the file " filename ". If not, see\n"))
	 (insert (concat comment " <https://github.com/davidam/workingclasslicense>.\n")))))
